server:
  port: 9000
  servlet:
    context-path: /foodhub
jwt:
  secret: jM96wA65XjOpAD8J01p6FCTb57x7mnLkWOGd1/2uQ2Y4w5cavSP9aPORUd4r2OSN
  lifetime: 30m
spring:
  application:
    name: delivery-api
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/foodhub_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data
  mail:
    host: smtp.gmail.com
    port: 587
    username: branets.web.development@gmail.com
    password: paneljfzapgcztvb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
