name: Java CI with Maven

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    name: Build delivery-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./delivery-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run:
          mvn clean package jib:dockerBuild -DskipTests
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/food-delivery-api